/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BetButton: typeof import('./src/components/Play/BetButton.vue')['default']
    BetDialog: typeof import('./src/components/Play/BetDialog.vue')['default']
    Coin: typeof import('./src/components/Coin.vue')['default']
    Drawer: typeof import('./src/components/NavigationBar/Drawer.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Hand: typeof import('./src/components/Play/Hand.vue')['default']
    HomePageCarousel: typeof import('./src/components/HomePageCarousel.vue')['default']
    LoginDialog: typeof import('./src/components/LoginDialog.vue')['default']
    NavBarButton: typeof import('./src/components/NavigationBar/NavBarButton.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar/NavigationBar.vue')['default']
    PogCards: typeof import('./src/components/PogCards.vue')['default']
    Pogs: typeof import('./src/components/Play/Pogs.vue')['default']
    PogsFlip: typeof import('./src/components/PogsFlip.vue')['default']
    PogShopCard1: typeof import('./src/components/Shop/PogShopCard1.vue')['default']
    PogShopCard2: typeof import('./src/components/Shop/PogShopCard2.vue')['default']
    PogShopCard3: typeof import('./src/components/Shop/PogShopCard3.vue')['default']
    PogShopCard4: typeof import('./src/components/Shop/PogShopCard4.vue')['default']
    PogShopCards: typeof import('./src/components/PogShopCards.vue')['default']
    RegisterDialog: typeof import('./src/components/RegisterDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInDialog: typeof import('./src/components/SignInDialog.vue')['default']
    Timer: typeof import('./src/components/Timer.vue')['default']
  }
}
